name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@main
      
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Build and Push Image to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: bw5bwcemigrationtask.azurecr.io
        username: aBW5BWCEMIGRATIONTASK
        password: uoRZcXAK8C3CBxU+97wSZTYjs8JPwmisrDw3X4kWng+ACRDrt2kh
    - run: |
        docker build --tag bw5bwcemigrationtask.azurecr.io/demo:${{ github.sha }} .
        docker push bw5bwcemigrationtask.azurecr.io/demo:${{ github.sha }}
