name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Build and Push Image to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: acrappsteer01.azurecr.io
        username: acrappsteer01
        password: T0Y2upicKm+Nh0Ejy01ihBDhAgwuc2xq
    - run: |
        docker build --tag "docker-hello-world:latest" .
        docker push docker-hello-world:latest
