name: SonarQube Analysis

on:
  push:
    branches:
      - master  # or the branch you want to run the analysis on
  pull_request:
    branches:
      - master  # or the branch you want to run the analysis on

jobs:
  sonarQube:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # or 'adopt'
        java-version: '11'

    - name: Cache SonarQube dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Install dependencies (Maven)
      run: mvn clean install

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
